---
- name: 'Update and upgrade packages on server.'
  become: yes
  apt:
    upgrade: yes
    update_cache: yes

- name: remove unneeded deps 
  become: yes
  apt:
    autoremove: yes

- name: "Install dependencies" 
  become: yes
  apt:
    name: ['nodejs', 'npm']
    state: latest
    update_cache: yes
  
- name: "install PM2 dependencies"
  become: yes
  npm:
    name: pm2
    global: yes
    state: latest
    production: yes