---
- name: 'Update and upgrade packages using on the server'
  become: yes
  apt:
    upgrade: yes
    update_cache: yes
   
- name: 'Remove redundant dependencies'
  become: yes
  apt:
    autoremove: yes

- name: 'Install dependencies'
  become: yes
  apt:
    name: ['nodejs', 'npm']
    state: latest
    update_cache: yes

- name: 'Install PM2 for the server'
  become: yes
  npm:
    name: pm2
    global: yes
    state: latest
    production: yes

- name: 'Extract/copy artifact from local machine to server'
  become: yes
  unarchive:
    src: files/artifact.tar.gz
    dest: .

- name: 'Start/unzip artifact'
  become: yes
  shell: |
    pm2 delete all
    pm2 start npm -- start